"""Email push channel — full HTML digest via SMTP (aiosmtplib)."""

from __future__ import annotations

import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib

from paper_distill_pro.config import settings
from paper_distill_pro.models import Digest

logger = logging.getLogger(__name__)


def _build_html(digest: Digest) -> str:
    rows: list[str] = []
    for section in digest.sections:
        rows.append(
            f"<h2 style='color:#1a5ca8;border-bottom:2px solid #d6e4f7;padding-bottom:6px'>"
            f"🔍 {section.keyword}</h2>"
        )
        for paper in section.papers[:6]:
            authors_str = ", ".join(a.name for a in paper.authors[:4])
            if len(paper.authors) > 4:
                authors_str += " et al."
            url = paper.oa_url or paper.url or ""
            title_html = (
                f'<a href="{url}" style="color:#1a5ca8;text-decoration:none">{paper.title}</a>'
                if url
                else paper.title
            )
            snippet = ""
            if paper.abstract:
                snippet = f"<p style='color:#6b7280;font-size:13px;margin:4px 0'>{paper.abstract[:200]}…</p>"
            rows.append(f"""
<div style='margin:14px 0;padding:14px;background:#f8f9fa;border-radius:8px;border-left:4px solid #1a5ca8'>
  <h3 style='margin:0 0 4px;font-size:15px'>{title_html}</h3>
  <p style='margin:2px 0;color:#6b7280;font-size:12px'>
    {authors_str} · {paper.year} · ⭐ {paper.citation_count} citations
  </p>
  {snippet}
</div>""")
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8"><title>{digest.title}</title></head>
<body style='font-family:system-ui,sans-serif;max-width:680px;margin:0 auto;padding:24px;color:#111'>
  <h1 style='color:#111;font-size:22px'>{digest.title}</h1>
  <p style='color:#6b7280'>{digest.date} · {digest.total_papers()} papers</p>
  <hr style='border:none;border-top:1px solid #e5e7eb'>
  {"".join(rows)}
  <hr style='border:none;border-top:1px solid #e5e7eb;margin-top:32px'>
  <p style='color:#9ca3af;font-size:11px'>Generated by paper-distill-pro · {digest.generated_at[:10]}</p>
</body></html>"""


async def send_email(digest: Digest) -> bool:
    if not all(
        [
            settings.smtp_username,
            settings.smtp_password,
            settings.smtp_from,
            settings.smtp_recipients,
        ]
    ):
        logger.warning("SMTP not fully configured — skipping email")
        return False
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"{digest.title} — {digest.date}"
    msg["From"] = settings.smtp_from
    msg["To"] = ", ".join(settings.smtp_recipients)
    msg.attach(MIMEText(_build_html(digest), "html", "utf-8"))
    try:
        await aiosmtplib.send(
            msg,
            hostname=settings.smtp_host,
            port=settings.smtp_port,
            username=settings.smtp_username,
            password=settings.smtp_password,
            start_tls=True,
        )
        logger.info("Email digest sent to %d recipients", len(settings.smtp_recipients))
        return True
    except Exception as exc:
        logger.error("Email push failed: %s", exc)
        return False
