"""Feishu (飞书) push channel — interactive card digest via group webhook bot."""

from __future__ import annotations

import logging

import httpx

from paper_distill_pro.config import settings
from paper_distill_pro.models import Digest

logger = logging.getLogger(__name__)


def _build_card(digest: Digest) -> dict:
    """Build a Feishu interactive card payload for the digest."""
    elements: list[dict] = [
        {
            "tag": "markdown",
            "content": (
                f"**📚 {digest.title}**\n> {digest.date} · 共 **{digest.total_papers()}** 篇论文\n"
            ),
        },
        {"tag": "hr"},
    ]

    for section in digest.sections:
        paper_items: list[dict] = []
        for paper in section.papers[:5]:
            authors_str = ", ".join(a.name for a in paper.authors[:2])
            if len(paper.authors) > 2:
                authors_str += " et al."
            url = paper.oa_url or paper.url or ""
            title_md = f"[{paper.title}]({url})" if url else paper.title
            meta = f"{authors_str} · {paper.year} · ⭐ {paper.citation_count}"
            paper_items.append(
                {
                    "tag": "markdown",
                    "content": f"• **{title_md}**\n  {meta}",
                }
            )

        elements.extend(
            [
                {
                    "tag": "markdown",
                    "content": f"### 🔍 {section.keyword}",
                },
                *paper_items,
                {"tag": "hr"},
            ]
        )

    elements.append(
        {
            "tag": "note",
            "elements": [{"tag": "plain_text", "content": "Generated by paper-distill-pro"}],
        }
    )

    return {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "content": f"📚 {digest.title}"},
                "subtitle": {
                    "tag": "plain_text",
                    "content": f"{digest.date} · {digest.total_papers()} papers",
                },
                "template": "blue",
            },
            "elements": elements,
        },
    }


async def send_feishu(digest: Digest) -> bool:
    """
    Send a paper digest to a Feishu group via incoming webhook bot.

    Requires FEISHU_WEBHOOK_URL in settings, e.g.:
    https://open.feishu.cn/open-apis/bot/v2/hook/xxxxx
    """
    if not settings.feishu_webhook_url:
        logger.warning("FEISHU_WEBHOOK_URL not set — skipping")
        return False
    try:
        payload = _build_card(digest)
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(settings.feishu_webhook_url, json=payload)
            resp.raise_for_status()
            result = resp.json()
            if result.get("code") and result["code"] != 0:
                logger.error("Feishu API error: %s", result.get("msg"))
                return False
        logger.info("Feishu digest sent (%d papers)", digest.total_papers())
        return True
    except Exception as exc:
        logger.error("Feishu push failed: %s", exc)
        return False
