"""WeCom (企业微信) push channel — group robot webhook, Markdown format."""

from __future__ import annotations

import logging

import httpx

from paper_distill_pro.config import settings
from paper_distill_pro.models import Digest

logger = logging.getLogger(__name__)


def _format(digest: Digest) -> str:
    lines = [f"## 📚 {digest.title}", f"> {digest.date}，共 **{digest.total_papers()}** 篇", ""]
    for section in digest.sections:
        lines.append(f"### 🔍 {section.keyword}")
        for paper in section.papers[:4]:
            authors_str = ", ".join(a.name for a in paper.authors[:2])
            if len(paper.authors) > 2:
                authors_str += " 等"
            url = paper.oa_url or paper.url or ""
            title_part = f"[{paper.title}]({url})" if url else paper.title
            lines.append(
                f"- **{title_part}**\n  {authors_str}（{paper.year}）· ⭐ {paper.citation_count}"
            )
        lines.append("")
    lines.append("*Generated by paper-distill-pro*")
    return "\n".join(lines)


async def send_wecom(digest: Digest) -> bool:
    if not settings.wecom_webhook_url:
        logger.warning("WECOM_WEBHOOK_URL not set — skipping")
        return False
    try:
        async with httpx.AsyncClient(timeout=15.0) as client:
            resp = await client.post(
                settings.wecom_webhook_url,
                json={"msgtype": "markdown", "markdown": {"content": _format(digest)}},
            )
            resp.raise_for_status()
            logger.info("WeCom digest sent (%d papers)", digest.total_papers())
            return True
    except Exception as exc:
        logger.error("WeCom push failed: %s", exc)
        return False
